runtime: python39
default_expiration: "7d"

handlers:
- url: /images
  static_dir: static/images

- url: /videos
  static_dir: static/videos

- url: /js
  static_dir: static/js

- url: /runs
  static_dir: static/runs
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /css
  static_dir: static/css
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /resume.pdf
  static_files: static/resume/resume.pdf
  upload: static/resume/resume.pdf

- url: /robots.txt
  static_files: static/crawler/robots.txt
  upload: static/crawler/robots.txt

- url: /sitemap.xml
  static_files: static/crawler/sitemap.xml
  upload: static/crawler/sitemap.xml

- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301
