runtime: python27
api_version: 1
threadsafe: false

default_expiration: "7d"

handlers:
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css
  http_headers:
    Access-Control-Allow-Origin: "*"
    
- url: /robots.txt
  static_files: static/crawler/robots.txt
  upload: static/crawler/robots.txt

- url: .*
  script: main.py
  secure: always
  redirect_http_response_code: 301

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on
